[theme]
primaryColor = "#283171"     # Mar - tecnologia, confiança
backgroundColor = "#ffffff"  # Branco - clareza, espaço
secondaryBackgroundColor = "#dde3eb"  # Neblina - calma, possibilidades
textColor = "#0c0c21"        # Sideral - poder, força
font = "sans serif"

